function list=list_of_seismic_functions
list={ ...
0,'ava_approximation','Compute approximate amplitude vs angle of incidence (AVA)';
0,'ava_approximation4model','Compute approximate amplitude vs angle of incidence (AVA) for a model';
0,'phase_time_shifter','Compute coefficients of zero-gain ARMA filter for phase shift';
1,'read_segy_file','Read disk file in SEG-Y format';
1,'s_2d_spliced_synthetic','Plot synthetic spliced into seismic line';
0,'s_arma_filter','Apply ARMA filter to seismic data set';
0,'s_3d_header_plot','Make contour plot of one header as function of two others';
1,'s_3d_spliced_synthetic','Plot synthetic spliced into inline and cross-line of 3-D data set';
0,'s_adapt_reflectivity','Modify reflectivity to improve match between synthetic and seismic';
1,'s_align','Align/flatten events on seismic data set via correlation';
0,'s_align_pt','Align/flatten events (peaks, troughs, zero crossings) on seismic data set';
0,'s_align2reference','Align seismic traces to a reference trace';
1,'s_append','Append one seismic data set to another seismic data set';
0,'s_ava_approximation','Compute angle-dependent reflectivity (AVA) for data in a model structure';
0,'s_ava4shale_sand_shale','Compute seismic data for random sand-shale models and range of angles'; 
0,'s_avapar2gather','Create gather with angle-dependent reflectivities from AVA parameters';
1,'s_check','Check seismic data set for formal errors/mistakes, missing fields, etc.';
0,'s_beautify_wavelets','Appends/prepends (if not present) zeros to wavelets to beautify their display';
0,'s_bootstrap_mean','Compute mean and standard dev. of mean of traces via the bootstrap method';
1,'s_compare','Plot one seismic data set on top of another for comparison';
1,'s_convert','Create a minimal seismic structure from a matrix';
1,'s_convolve','Convolve two seismic data sets';
0,'s_constant_phase_wavelet','Estimate constant-phase wavelet from seismic and reflectivity (untested)';
1,'s_correlate','Compute cross-correlation of the traces of two seismic data sets';
1,'s_cplot','Plot seismic data in form of color-coded pixels (for larger data sets)';
0,'s_create_reflections','Create reflection traces for testing of Euclid algorithm'; 
1,'s_create_qfilter','Create constant-Q absorption filters';
1,'s_create_wavelet','Create wavelet (minimum-phase, zero-phase, maximum-phase, Ricker)';
0,'s_cross_section','Create/model a cross-section with linearly interpolated reflectors';
1,'s_data','Create a test/demo data set (12 traces of filtered random noise; 1 sec long)';
0,'s_depth2time','Convert seismic data in depth to seismic data in time';
0,'s_euclid6','Estimate wavelet (one length) and reflectivity using Euclid (common-wavelet) algorithm';
0,'s_euclid_refl','Use Euclid (common-wavelet) algorithm to estimate wavelet and reflectivity';
1,'s_exp_scaling','Apply exponential scaling to each trace of a seismic data set';
0,'s_fdecon','Perform deterministic deconvolution in the frequency domain';
1,'s_fft','Compute Fourier transform (amplitude spectrum) of seismic traces';
1,'s_filter','Apply Ormsby-type band-pass filter to seismic data';
0,'s_find_impedance_stretch6','Stretch/squeeze a seismic trace (synthetic) to match a reference trace';
1,'s_frequency_attributes','Compute bandwidth and median frequency of a seismic data set';
1,'s_attribute','Compute functionals (max, mean, ...) of seismic traces and store them in headers';
1,'s_gain','Compute and apply gain (AGC) to a seismic data set';
1,'s_gd','Get description of a header of a seismic data set';
1,'s_gh','Get header values of a seismic data set';
0,'s_ghost_response','Apply effect of source/receiver ghost on seismic data set';
1,'s_gu','Get units of measurement of a header of a seismic data set';
1,'s_header','Add/delete/replace/display headers of a seismic data set';
1,'s_header_int2double','Convert bit pattern of integers in header to floating point numbers';
1,'s_header_math','Add/replace headers of a seismic data set by manipulating existing headers';
1,'s_header_plot','Plot header values of a seismic data set';
1,'s_header_sort','Sort seismic header value(s); output index vector (to sort seismic traces)';
1,'s_hilbert','Compute Hilbert transform or instantaneous amplitude of seismic data';
1,'s_histogram','Compute histogram of seismic amplitudes';
1,'s_history','Manipulate/display history field of a seismic data set';
0,'s_horizon_values','Compute seismic amplitude at a time that is stored in a header';
1,'s_impedance','Compute impedance from reflection coefficients';
0,'s_insert_deviated_synthetic','Insert synthetic into seismic along well track';
1,'s_iplot','Like "s_wplot", but with menu-based interactive plot parameter selection';
1,'s_ispectrum','Interactively pick windows on seismic plot and compute spectra of data in these windows';
0,'s_log_extrapolation','Extrapolate impedance log by means of seismic data';
1,'s_log2reflectivity','Create reflection coefficient series from well log in depth or time';
1,'s_log2seismic','Convert log curves to seismic traces';
1,'s_multi2one_trace','Convert a multi-trace data set into a one-trace data set vector';
1,'s_min_phase_inverse','Compute the minimum-phase_inverse of a wavelet or a data set';
1,'s_noise','Compute zero-mean noise with the same structure as the input data set';
1,'s_new_time','Change to new "time" axis (e.g. convert time to depth or stretch/squeeze seismic traces)';
1,'s_normalize','Normalize seismic traces to a specific value of an attribute (e.g. RMS amplitude)';
1,'s_one2multi_trace','Combine the traces of a data set vector into one multi-trace data set';
0,'s_pattern_response','Apply effect of source/receiver pattern on seismic data set';
1,'s_phase_rotation','Rotate phase of each trace of input data set by given amount(s)';
0,'s_pick4euclid','Interactively pick seismic segments for Euclid (Common-Signal) Wavelet Estimation';
1,'s_plot','"Quick-look" plot of seismic data (color if more than 101 traces, wiggle otherwise)';
0,'s_plot_spectra_wavelet_seismic','Plot wavelet and spectra of wavelet, seismic, and synthetic';
0,'s_pmo','Eugene Lichman''s phase moveout';
1,'s_power_spectrum','Compute power spectrum or amplitude spectrum of seismic traces';
1,'s_principal_components','Principal-component decomposition/analysis/smoothing';
0,'s_refl2impedance','Compute impedance from reflection coefficients';
0,'s_reflections4shale_shale_model','Compute reflection record for random shale-shale model';
0,'s_reflections4shale_sand_shale_model','Reflection coefficients for random shale/gross-sand/shale model';
1,'s_reflcoeff','Compute reflection coefficients from impedance';
1,'s_resample','Resample seismic data set to higher or lower sample rate';
1,'s_rm_trace_nulls','Remove leading/trailing Null values common to all traces; replace other NaNs with zeros';
1,'s_rm_traces','Remove traces which have one NaN or have only NaNs (null values)';
1,'s_rm_trend','Removes means/bias, medians, trends, etc. from traces of seismic data set';
1,'s_rm_zeros','Remove leading/trailing zeros common to all traces and adjust times of first/last sample';
1,'s_scale_seismic_data_sets','Compute scale factors to match two seismic data sets';
1,'s_roots2wavelet','Compute wavelet from the roots of its z-transform';
1,'s_seismic2wavelet','Compute wavelet with spectrum of seismic (min-phase, max-phase, zero-phase)';
0,'s_seismic2wavelets','Compute wavelets(min/max/zero-phase) with spectrum of seismic from randomly chosen traces';
1,'s_select','Select range of time and/or traces of a seismic data set';
1,'s_select_polygon','Select subset of a 2-D data set either inside or outside a polygonal region';
1,'s_shift','Apply time shifts to seismic traces';
0,'s_signal_comparison','Compute dissimilarity between traces of two data sets; store result in header';
0,'s_signal_parameters','Compute/print/store in header wavelet/signal phase, median frequency, bandwidth';
1,'s_spectrum','Plot amplitude and/or phase spectra of one or more seismic data sets';
0,'s_spick1','Interactively pick time/trace pairs from a plot of seismic data (at most one pick per trace)';
1,'s_seismic4jason','Write seismic data to ASCII file in Jason format ';
1,'s_spectrum2wavelet','Compute zero-phase wavelet from amplitude spectrum';
0,'s_spicks','Interactively pick time/trace pairs from a plot of seismic data (no restriction on number of picks/trace)';
1,'s_stack','Stack seismic data';
0,'s_synthetic_wm','Compute synthetic seismogram with/without multiples (Goupillaud)';
1,'s_synthetic4landmark','Write synthetic to ASCII file for use in Landmark';
0,'s_table2headers','Add headers from a table to a seismic data set'; 
0,'s_test_gather','Create a synthetic gather with no, with linear, or, with hyperbolic moveout';
0,'s_time2depth','Convert seismic data in time to seismic data in depth';
1,'s_tools','Show available seismic tools';
1,'s_trace_numbers','Get sequential trace numbers of seismic traces selected via header values';
0,'s_track_well','Extract seismic trace segments (or a single trace) along a deviated well';
0,'s_tv_spectrum','Compute time-varying spectrum and from it median frequency and bandwidth';
0,'s_utils','Show useful, seismic-related  utilities';
0,'s_waavo_inversion','Invert angle gather for elastic parameters (wide-angle AVA inversion)';
0,'s_wb_time','Compute approximate time to the water bottom reflection (water depth)';
1,'s_wavelet2roots','Compute the roots of the z-transform of a wavelet';
1,'s_wavelet4landmark','Write wavelet to ASCII file in Landmark format';
1,'s_wavelet_from_landmark','Read wavelet from ASCII file in Landmark format';
1,'s_wavelet_from_hr','Read wavelet from ASCII file in Hampson-Russell format';
0,'s_wavelet_comparison','Compare and interactively time-shift, phase-shift, and scale wavelets';
0,'s_wavelet_matching','Compute Wiener filter that matches wavelet(s) to target wavelet(s)'; 
0,'s_wavelet_stretch','Stretch wavelet in an angle-dependent way to simulate NMO stretch';
0,'s_wavest','Extract/estimate wavelet from seismic data and reflection coefficients';
1,'s_wavextra','Extract/estimate wavelet from seismic data and reflection coefficients';
0,'s_well_track','Compute seismic traces along a well trajectory';
0,'s_wedge_model','Compute/plot synthetic from wedge model and the tuning curve derived from it';
1,'s_wiener_filter','Compute Wiener filter to match one seismic data set to another';
1,'s_window','Apply a window to seismic data';
1,'s_wplot','Plot seismic data in wiggle-trace format';
1,'s_wplot_with_header','Plot selected headers above seismic in wiggle-trace format';
1,'s_zero_phase','Create the zero-phase equivalent of the input data set';
1,'show_segy_header','Read/Output/Display EBCDIC header of SEG-Y file in ASCII form';
0,'si_header_plot','Interactively select three headers to plot';
0,'si_select','Interactively select and/or edit seismic trace headers';
1,'write_segy_file','Write disk file in SEG-Y format (big-endian IEEE floating-point format)'};
